### ISSUE TITLE
New URL

### ISSUE THREAD

**Issue by basst85** [timvisee/ban-binance-bot#1]
This URL was not recognised as spam: 
`[REDACTED]`

**Comment by timvisee** [comment]
Thanks! Will add this as well, soon.

Just wondering, did this indeed bypass the bot? Webpages linked to are scanned as well, it could mean there's a problem with this system.

**Comment by basst85** [comment]
> Thanks! Will add this as well, soon.
> 
> Just wondering, did this indeed bypass the bot? Webpages linked to are scanned as well, it could mean there's a problem with this system.

Yes, because the Binance bot not edited the message correctly :-)
![image](https://user-images.githubusercontent.com/6396615/66735258-2bc64600-ee66-11e9-9e0f-85c811e1a060.png)
